project:
  type: website
  preview:
    port: 8080
    host: localhost
  resources:
    - "CNAME"
website:
  title: "Witness Journal APS"
  site-url: "https://soci.witnessjournal.com"
  description: "Dati sull'Associazione WJ"
  margin-footer: |
    - Copyright 2020
    - APS Witness Journal
    - CF: 97739350151 
    - PEC: <witnessjournal@pec.it>
  navbar:
    left:
      - text: "{{< bi people >}} Direttivo"
        href: direttivo.qmd
      - text: "{{< bi geo >}} Territori"
        href: territori.qmd
      - text: "{{< bi bar-chart >}} Situazione Soci"
        href: situazione_soci.qmd
      - text: "{{< bi graph-up >}} Storico"
        href: storico.qmd
format:
  html:
    lang: it-IT
    toc: true
    email-obfuscation: "javascript"
    theme: 
      - wj.scss